### ISSUE TITLE
vue hot reload do not work in nested component

### ISSUE THREAD

**Issue by liyangready** [vuejs/vue-loader#507] opened 2016-11-30 14:43 UTC
```
<parent>
   <child></child>
</parent>
```
modify the child component cannot trigger hot replace.
```
<div>
 <child></child>
</div>
```
modify the child component can trigger hot replace.

**Comment by yyx990803** [comment] 2016-11-30 17:41
Cannot reproduce with latest version. Are you using 0.8 with Vue 1?

**Comment by liyangready** [comment] 2016-12-01 05:47
Thanks for reply! 
I create project from latest vue-cli:  `vue init webpack test-vue-hot-reload`

 ```
    ...
    "vue-loader": "^10.0.0",
    "vue-style-loader": "^1.0.0",
    "vue-template-compiler": "^2.1.0",
```
here is my test project : 
[https://github.com/liyangready/test-vue-hot-reload](https://github.com/liyangready/test-vue-hot-reload)

reproduce steps:
**1. add slot in hello.vue**
```
<template>
  <div class="hello">
     ...
    <slot></slot>
  </div>
</template>
```

**2. add child.vue file**
```
<template>
<div>{{msg}}</div>
</template>

<script>
export default{
  name: 'child',
  data () {
    return {
      msg: 'i am child'
    }
  }
}
</script>
```
**3. modify App.vue template**
```
<hello>
   <child></child>
</hello>
```
**4. change child msg from 'i am child' to 'i am child change'**
. nothing happen.

**Comment by kazupon** [comment] 2017-01-06 17:43
Thank you for your reproduce code!
I also could not reproduce.

Closing tentatively.

Please re-open if you can follow up with more information. 😉

**Closed by kazupon** 2017-01-06 17:43 UTC

**Comment by liyangready** [comment] 2017-01-07 03:39
yes, it is already fixed in lasted version. Thank you !  If somebody met the same problem, update package can fix it.

**Comment by rootsli** [comment] 2017-01-24 12:43
I have the same problem, but it has been solved. It may be caused by the editor,for example webstorm。It has a function called "safe write" in the settings: settings=>appearance=>system=>synchornization=>last item。unchecked it, vue hot reload worked.
