### ISSUE TITLE
SSR vnode mismatch 

### ISSUE THREAD

**Issue by hirokiosame** [vuejs/vue-loader#974] opened 2017-09-14 07:30 UTC
### Version
13.0.4

### Reproduction link
[https://github.com/hirokiosame/vue-test-ssr](https://github.com/hirokiosame/vue-test-ssr)

### Steps to reproduce
1. Clone the ssr environment: https://github.com/hirokiosame/vue-test-ssr
2. `npm install` & `npm run dev`

### What is expected?
For the component to render fine in the backend and frontend.

### What is actually happening?
The SSR server is going to mount this simple component: https://github.com/hirokiosame/vue-test-component/blob/master/src/TestComponent.vue

It renders fine if it's just front-end rendering, but when using server-side rendering, it breaks with a vnode mismatch error: 

![screen shot 2017-09-14 at 12 29 45 am](https://user-images.githubusercontent.com/1075694/30417225-d7e1910e-98e3-11e7-9236-febde1861833.png)

---
The server is using NUXT version 1.0.0-rc8 which uses vue-loader@13.0.4 and vue@2.4.3
The component is using vue-loader@13.0.4 (the version wasn't on the list in the form btw)

**Comment by kazupon** [comment] 2017-09-14 10:01
hmm 🤔, I seem occured degression in Vue 2.4.3.
/ping @yyx990803

**Comment by yyx990803** [comment] 2017-09-14 15:55
Not really a regression, seems to be happening for 2.4.2 too.

**Comment by yyx990803** [comment] 2017-09-14 16:25
Fixed in Vue core. Will probably need to wait for the next patch release.

**Closed** 2017-09-14 16:25 UTC

**Comment by hirokiosame** [comment] 2017-09-14 17:06
Super fast. Thanks @yyx990803
