### ISSUE TITLE
Improve SourceMap Handling

### ISSUE THREAD

**Issue by auchenberg** [vuejs/vue-loader#1163] opened 2018-02-14 01:18 UTC
We on the VS Code team just released a [debugging recipe for Vue.js](https://github.com/Microsoft/vscode-recipes/tree/master/vuejs-cli), to allow our Chrome debugger to debug Vue, and during this release we discovered some fundamental problems with the sourcemaps generated by vue-loader used in the webpack projects generated by vue-cli,

**Observed problems**
- The generated sourcemaps seems to be invalid and unreadable for tools like https://sokra.github.io/source-map-visualization/
- Stepping in debuggers like Chrome DevTools and VS Code doesn't work as expected, as we experience "sliding breakpoints" caused by missing mappings that causes us to "slide" the breakpoint down to the next line we have mappings for. Causes experiences like:
![chromw1](https://user-images.githubusercontent.com/173559/36183088-9a214b2c-10e1-11e8-8017-33aa1f4ff232.gif)

- Mappings for simple statements seems to be missing/wrong, which causes debuggers to load the compiled source, which causes experiences like, where a breakpoint is set on line 94, but is in reality set in a different place. 
![chrome2](https://user-images.githubusercontent.com/173559/36183121-b6ce8b0e-10e1-11e8-879e-ba3445ea3e5d.gif)

- Generated entries for sourcefiles are added to the sourcemap under the `.` path, which creates confusion, as the files under `./src` are generated outputs, and not the original authoring abstraction. This is causing problems for debuggers like VS Code that relies on mappings between the _served bundle and the original original authoring abstraction._

<img width="772" alt="screen shot 2018-02-13 at 5 19 29 pm" src="https://user-images.githubusercontent.com/173559/36183233-44214c58-10e2-11e8-9c90-c0a8568d0fec.png">

In this example the original authoring abstraction is also referenced under `/src/components/HelloWorld.vue`

- Using `let` statements for variables seems to cause problems for the sourcemaps, as both VS Code and Chrome DevTools can't step over the statements, but stays on the same line when using step-over.

![chrome3](https://user-images.githubusercontent.com/173559/36183455-2a157f7c-10e3-11e8-96ad-27ce60aad26b.gif)

**Steps to reproduce**
1. Generate webpack project by vue-cli
2. Add a few new lines to line 90 in `HelloWorld.vue`, so you have logic like:
```
export default {
  name: 'HelloWorld',
  data () {
    var a = 1
    var b = 2
    var c = 3
    var d = a+c
    return {
        msg: 'Welcome to Your Vue.js App' + d
    }
  }
}
````
- Open up Chrome DevTools or the VS Code debugger, and try to set breakpoints in `HelloWorld.vue`

**Relevant issues**
- https://github.com/vuejs/vue-loader/issues/620
- https://github.com/Microsoft/vscode-recipes/issues/74

**Comment by gzzhanghao** [comment] 2018-04-01 17:49
I've built another sourcemap visualizer recently, and I found sourcemaps from vue-loader is kinda wired. [example](http://smv.http418.org/#/url/https%3A%2F%2Fapi.github.com%2Fgists%2F55a10afcd9de4dcff6388b0a3ef503a3)

**Comment by eladcandroid** [comment] 2018-04-24 07:37
Any news about this issue? I'm Still not able to debug correctly with VSCode

**Comment by xeor** [comment] 2018-04-25 05:37
I'm in the same boat... Maybe write a little "headsup" in `debugging recipe for Vue.js` while we wait.

**Comment by gzzhanghao** [comment] 2018-04-25 06:53
Related pr: https://github.com/babel/babel/pull/7761

**Comment by loganfsmyth** [comment] 2018-04-26 16:53
I've landed https://github.com/babel/babel/pull/7761 and backported it to Babel 6.x in https://github.com/babel/babel/pull/7812. It should now be out and available as `babel-core@6.26.2`.

I believe it should fix at least _some_ of the problems described here. I haven't worked through them specifically, but I'd expect it to make a big difference.

Please let me know if you run into any issues with the new release. I don't think that many tools actually use inputSourceMap, so Vue is probably likely to be one of the main projects to benefit from this.

**Comment by sobolevn** [comment] 2018-05-09 17:40
@loganfsmyth Thanks for addressing this! Unfortunately, still having some troubles: https://github.com/octref/veturpack/issues/13#issue-321656224

**Comment by yyx990803** [comment] 2018-05-11 03:28
@loganfsmyth this is awesome, can't wait for it to land in 7.x. I've tested it with `babel-core@6.26.3` and it works perfectly now (able to set breakpoints in devtools as well)!

**Comment by qiulang** [comment] 2018-05-15 09:18
I upgraded babel-core@6.22 to babel-core@6.26, it did fix the "sliding breakpoints"  for me!

**Comment by gkatsanos** [comment] 2018-07-10 09:37
I would like to bring your attention to a related bug I raised in JETBRAINS/Webstorm which might be related to how vue-loader handles source maps. : https://youtrack.jetbrains.com/issue/WEB-33793 
I also raised this in the webpack issue tracker: https://github.com/webpack/webpack/issues/7199

**Comment by rjgotten** [comment] 2018-08-27 13:58
So... has anyone ever figured out what is generated all the intermediate source maps?

Frankly, that trash - And really; it is trash. It serves absolutely zero purpose. - has been growing to be such an eye-sore and impedement on developer ergonomics that I've begun considering writing a webpack plugin to post-process source maps with the explicit goal of forcefully evicting everything that matches the `/\.vue\?[a-z0-9]{4}$/` regex.

**Comment by yyx990803** [comment] 2018-08-27 18:01
@rjgotten this was mostly caused by Babel not expecting the source map being passed on for new source map generation. This has been fixed in the latest versions of Babel. If you have other cases where Source Maps are not working properly, please open a separate issue with proper information.

**Closed by yyx990803** 2018-08-27 18:01 UTC
Labels: improvement
