### ISSUE TITLE
Typo in .vue template causes stuck?

### ISSUE THREAD

**Issue by wYhooo** [vuejs/vue-loader#593] opened 2017-01-26 03:22 UTC
This issue is an update of [this one](https://github.com/vuejs-templates/webpack/issues/462).
I found a strange thing that if you type this 
`<a>< /a>` 
or something like this 
`<a><img :src="img.path">< /a>` 
(pay attention to the typo in the `< /a>` tag, a space is inserted)
in your .vue template, then run `npm run dev` / `npm run build` the node process will get stuck.
However this `<a>placeholder< /a>` will not cause that problem.

**Comment by kazupon** [comment] 2017-01-28 17:21
I could not reproduce this issue.
Can you provide the minimum reproduction repo please?

**Comment by wYhooo** [comment] 2017-01-29 04:48
1. init a project using `vue init webpack`
2. open `Hello.vue`
3. add `<a>< /a>` anywhere
4. `npm run dev`
5. your node process get stuck

**Comment by teknik2008** [comment] 2017-01-29 13:11
Same problem if you write `<div><</div>`
Hangs and not showing where the error.

**Comment by wYhooo** [comment] 2017-01-29 13:48
I think maybe `&lt;` is a better choice? :)

**Comment by teknik2008** [comment] 2017-01-29 13:58
Yes, that's right. I did just that. But I took the time to understand the error. I no one said where it is.

**Comment by kazupon** [comment] 2017-01-30 02:31
Hmmm, I reproduced this issue.

**Comment by kazupon** [comment] 2017-02-02 03:50
This is issue of vue core.
This issue already fixed with https://github.com/vuejs/vue/pull/4753
Close;

**Closed by kazupon** 2017-02-02 03:50 UTC
Labels: bug
