### ISSUE TITLE
Add a warning message when missing </script> end block in a .vue file

### ISSUE THREAD

**Issue by sylvainpolletvillard** [vuejs/vue-loader#1436] opened 2018-11-22 17:27 UTC
### What problem does this feature solve?
It happened to me twice in a week and I lost hours trying to figure out what was going on.
Currently,  when we forget to end the HTML script tag in a .vue component file, vue-loader does not emit any error. Instead, it assumes there is no script at all. So we usually get a runtime error instead, complaining that a property is not defined but referenced in the template. This is very confusing as we assume the script is parsed correctly but something is wrong with the component definition. But in fact, we just forget to close this script tag.
I know this fits in the facepalm category, but I thought that maybe vue-loader could do something better about it: shows a warning or automatically close the tag. This case is also not covered by eslint-plugin-vue latest beta.

### What does the proposed API look like?
A small warning message like "Did you forget to close your &lt;script&gt; tag ?" could save hours of frustration. Thanks !

**Comment by posva** [comment] 2018-11-22 18:46
Duplicate of https://github.com/vuejs/vue-loader/issues/1403

**Closed by posva** 2018-11-22 18:46 UTC
