### ISSUE TITLE
transpile (Babel) not just code in <code> but also code in <template>

### ISSUE THREAD

**Issue by zenflow** [vuejs/vue-loader#1555] opened 2019-06-15 18:28 UTC
### What problem does this feature solve?
I want to be able to apply a babel to all my code, not just the <script> part, but also the code expressions in <template> part.

I think it's of general usefulness to be able to apply any kind of transform on my code, whether it's a standard transform (i.e. new es features) or some kind of a custom transform.

In my particular case I want to work with calls to a gettext-like function (e.g. `$t('Localized message')` which are in the <template> more often than not. I have two jobs to do this way: 1. Extract the static message strings 2. Replace the static message strings with an object containing locales data. 

The best solution I found to work around this is basically to run everything through babel twice: first to get everything into pure js, and second to do the work, but that has huge disadvantages 
 - we're no longer working with the representation of the *source* code 
 - much more expensive to the build in terms of CPU cycles (time)

### What does the proposed API look like?
No new API, but the behavior would be just as described in the title: transpile (Babel) not just code in `<code>` but also code in `<template>`

I would be happy to take a shot at making this PR if maintainer can approve the feature request!

**Comment by Justineo** [comment] 2019-06-16 02:34
Duplicate of https://github.com/vuejs/vue/issues/6307

Vue is currently transpiling template with a [fork](https://github.com/yyx990803/buble) of [Bublé](https://buble.surge.sh/guide/) so it requires quite a lot of work to switch to Babel IMO.

**Closed by Justineo** 2019-06-16 02:34 UTC
