### ISSUE TITLE
v-model compiling fails when used with functional components

### ISSUE THREAD

**Issue by miljan-aleksic** [vuejs/vue-loader#1539] opened 2019-04-18 13:50 UTC
### Version
15.7.0

### Reproduction link
[https://codesandbox.io/s/r58jr04jlo](https://codesandbox.io/s/r58jr04jlo)

### Steps to reproduce
Click on the checkbox.

### What is expected?
The checkbox should be selected without throwing js errors.

### What is actually happening?
It's issuing an error becasue the compiled js code assumes it's a stateful component and tries to use `_vm.$set()`.

**Comment by posva** [comment] 2019-04-18 13:52
Marking as both as I don't know if this was intended to work in the first place

**Comment by yyx990803** [comment] 2019-04-19 01:19
While I think this should technically work, I strongly suggest staying away from such usage.

1. Functional component being able to mutate parent state is very implicit and not a good pattern.

2. `<template functional>` is likely going away in v3. (See https://github.com/vuejs/rfcs/pull/27)

I'll close this as a wontfix.

**Closed by yyx990803** 2019-04-19 01:19 UTC
Labels: bug, feature request
