### ISSUE TITLE
When loader some wrong syntax of .vue file, cpu of node will rise to 100%.

### ISSUE THREAD

**Issue by TongchengQiu** [vuejs/vue-loader#682] opened 2017-03-02 02:51 UTC
node version: v4.6.0
vue-loader version: 11.1.3

This is my webpack config:
(index.js)
```javascript
var webpack = require('webpack');
var path = require('path');

var config = {
  entry: './demo.vue',
  output: {
    path: './',
    filename: 'build.web.js'
  },
  module: {
    loaders: [{
        test: /\.vue(\?[^?]+)?$/,
        loaders: ['vue-loader']
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/,
        query: {
          presets: ['es2015'],
          plugins: ['transform-runtime']
        }
      }
    ]
  },
  resolve: {
    root: path.join('./', 'node_modules')
  }
}
var compiler = webpack(config)

try {
  compiler.run(function (err, stats) {
    console.log(err);
    console.log(stats);
  });
} catch (e) {}
```

This is my demo.vue file will be packed:
```vue
<template>
  <div class="title_bar_div">
    <div class="title_bar_back">

      <!--><img class="title_bar_back_img" src="../img/ic_back_black_24dp.png" height="48" width="48"/><-->

    </div>
  </div>
</template>

<style>
  .title_bar_div {
    background-color: white;
    width: 750px;
    height: 100px;
  }
  .title_bar_back{
    width:100px;
    height: 100px;
    background-color: white;
    align-content: center;
  }
  .title_bar_back:active{
    width:100px;
    height: 100px;
    background-color: gray;
    align-content: center;
  }
  .title_bar_back_img{
    justify-content: center;
    align-items: center;
  }
</style>

<script>

  module.exports = {
    props: {
      title: { default: '456' },
      url: { default: '' }
    },
    components: {

    },
    methods: {
      redirect: function() {
      }
    }
  }
</script>
```

When run `node index.js`, node cpu will rise to 100% because my .vue file has one wrong syntax:
```javascript
...
<!--><img class="title_bar_back_img" src="../img/ic_back_black_24dp.png" height="48" width="48"/><-->
...
```

**Comment by Lucassifoni** [comment] 2017-03-06 23:59
Yeah, the HTML parser goes in an infinite loop when it encounters what seems to be misformed opening/closing tags, from what I've tried.

```html
<template>
  <div>
    <div><</div>
    <div><</div>
  </div>
</template>
```

is enough to make it unresponsive.
Maybe it should issue a warning.

Nevertheless, for now, if you need to display < > characters directly inside HTML tags, you can escape them with &lt; and &gt;

**Comment by yyx990803** [comment] 2018-03-06 23:24
Closing outdated issues - if the problem still persists in the latest version, please open a new issue using the [issue helper](new-issue.vuejs.org/?repo=vuejs/vue-loader) with a reproduction. Thanks.

**Closed by yyx990803** 2018-03-06 23:24 UTC
