### ISSUE TITLE
Cant use props with webpack

### ISSUE THREAD

**Issue by tcetin** [vuejs/vue-loader#670] opened 2017-02-23 09:22 UTC
Props cant works on webpack and vue-loader.Also discussed on https://laracasts.com/discuss/channels/vue/cant-use-props-on-single-file-component?page=1

**Comment by LinusBorg** [comment] 2017-02-23 09:34
Props work 100% fine with vue-loader and webpack, Everyone of us uses them all the time.

If you think your found a bug, please provide a repository that reproduces the problem specifically.

Otherwise, I consider this a support question, for which we provide a forum at forum.vuejs.org

**Comment by simplesmiler** [comment] 2017-02-23 09:52
Judging by your code example, you just got confused. You think you have two components (app and vue-test), where in fact you have just one.

You say `render: h => h(App)`, so the inline template `<vue-test url="foo.com"></vue-test>` gets lost, being replaced with the template of the `App` component.

Steps to take:
1. Rename `App.vue` to `VueTest.vue`.
2. Remove inline template from `index.html`, keeping it just `<div id="app"></div>`.
3. Create `App.vue` with the following content:
``` vue
<template>
  <vue-test url="foo.com"></vue-test>
</template>
<script>
  import VueTest from './VueTest.vue'
  export default {
    components: { VueTest }
  }
</script>
```

As @LinusBorg said, issue list is not a good place to post unless you are sure you have found a bug or want to discuss a new feature.

**Comment by tcetin** [comment] 2017-02-23 09:59
Thanks for reply. But I am trying on index.html. Not vue template.So I want to get url that users whatever write.But I could gain this till now. In laravel works perfectly but in vue-loader with wepack-simple doesnt work.

**Comment by LinusBorg** [comment] 2017-02-23 12:04
As this is certainly not a bug, I will close this. Please open a thread on our forums for further support.

**Closed by LinusBorg** 2017-02-23 12:04 UTC
Labels: need repro
