### ISSUE TITLE
.vue file, webpack converts background-image relative path to local path

### ISSUE THREAD

**Issue by yezongyang** [vuejs/vue-loader#284] opened 2016-07-12 07:48 UTC
![uf4h6 _4 y02 wj5 jzik](https://cloud.githubusercontent.com/assets/8924156/16759132/0f51c8e0-4848-11e6-8ea1-b71a4794c77e.png)

**Comment by LinusBorg** [comment] 2016-07-12 07:57
Hello @yezongyang 

Thanks for filing this issue. can you provide the webpack configuration that leads to this behaviour? A reproduction on webpackbin.com would be awesome.

**Comment by yezongyang** [comment] 2016-07-12 08:03
webpack config

![u0cesmb yuz57 xy058f1i](https://cloud.githubusercontent.com/assets/8924156/16759570/3902da38-484a-11e6-92ad-eab819f54e67.png)

**Comment by LinusBorg** [comment] 2016-07-12 08:13
you have set your `publicPath` to an absolute path on your file system.

CSS Loader rewrites all asset paths in CSS to match the path according to this setting.

it should probably look like this (but can't say for sure since I don't fully see how your output files are arranged):

    publicPath: '/'

See docs: https://webpack.github.io/docs/configuration.html#output-publicpath

> The publicPath specifies the public **URL address** of the output files when referenced in a browser.

**Comment by LinusBorg** [comment] 2016-07-12 08:14
Closing this as it's not a bug.

For further support, feel free to post on forum.vuejs.org or gitter.im/vuejs/vue

**Closed by LinusBorg** 2016-07-12 08:14 UTC
Labels: need repro
