### ISSUE TITLE
Duplicated css module file when using `@value ... from ...` inside `<style module>` block

### ISSUE THREAD

**Issue by fnlctrl** [vuejs/vue-loader#1199] opened 2018-03-21 14:27 UTC
### Version
14.2.1
Webpack 4.1.1

### Reproduction link
[https://github.com/fnlctrl/vue-loader-duplicate-cssm-import-repro](https://github.com/fnlctrl/vue-loader-duplicate-cssm-import-repro)

### Steps to reproduce
1. `npm install`

2. `npm run build`
Check dist/bundle.js, using js imported style works fine, `colors.css` is not duplicated`

3. Uncomment the `@value Red-500 from './colors.css';` line in app.vue, and `npm run build`
Check dist/bundle.js, you'll now see `colors.css` duplicated. 
This bug causes `colors.css` to be duplicated every time a component 
uses `@value ... from ...` inside `<style module>` block

### What is expected?
Only one `colors.css`

### What is actually happening?
Duplicated `colors.css`

**Comment by yyx990803** [comment] 2018-03-23 19:35
The root cause of this is that `css-loader` appends the importing module's inline loader request prefixes to all imported modules. So for `import 'css-loader?foo!colors.css'` and `import 'css-loader?bar!colors.css'`, any files imported by `colors.css` will be duplicated because technically they might need to be processed with different options.

This is unfortunately unfixable in v14. But I managed to get it resolved in v15.

**Closed by yyx990803** 2018-03-23 19:35 UTC
