### ISSUE TITLE
Doesn't work with webpack v4.29.0

### ISSUE THREAD

**Issue by Drezdenozk** [vuejs/vue-loader#1476] opened 2019-01-21 14:31 UTC
### Version
15.5.1

### Reproduction link
[https://codesandbox.io/s/pmyy7494x7](https://codesandbox.io/s/pmyy7494x7)

### Steps to reproduce
1. Install webpack 4.29.0, vue-cli latest.
2. try to load files like
    'components': {
      'a': () => import(`./a.vue`),
    },
3. vue-cli-service build --modern 

### What is expected?
Build completed

### What is actually happening?
Module parse failed: Unexpected token (22:9)
You may need an appropriate loader to handle this file type.

---
With webpack 4.28.4 works perfect

**Comment by sodatea** [comment] 2019-01-21 14:35
Duplicate of https://github.com/vuejs/vue-cli/issues/3335

**Closed by sodatea** 2019-01-21 14:35 UTC
