### ISSUE TITLE
vue-loader building performance

### ISSUE THREAD

**Issue by qbaty** [vuejs/vue-loader#435] opened 2016-10-31 12:00 UTC
I used vue-cli webpack template to build my project.
I build my project in production way cost 17411ms, before I optimized it the time is 42123ms.

![image](https://cloud.githubusercontent.com/assets/190570/19853252/16894112-9fa3-11e6-88df-fec5bcee106e.png)

I try improve build performance a little bit more. 
And I found out the those script content in .vue files will met the vue-loader rather than babel-loader.
So I want assign a loader for those script like the doc said, and want to use cacheDirectory for better performance like this.

![image](https://cloud.githubusercontent.com/assets/190570/19853409/06378dc2-9fa4-11e6-9926-113349e4ccfb.png)

Turns out time costs the same.
I use HappyPack for vue-loader.

![image](https://cloud.githubusercontent.com/assets/190570/19853557/e85fc502-9fa4-11e6-8ccd-9ddef786b0de.png)

![image](https://cloud.githubusercontent.com/assets/190570/19853562/f2a186d6-9fa4-11e6-9fb1-19322418aebc.png)

Any suggestion about improve my building performance will be helpful

**Comment by yyx990803** [comment] 2016-10-31 12:54
Are you saying using HappyPack reduced the time from 42s to 17s?

**Comment by qbaty** [comment] 2016-10-31 15:16
No, I did a few things.

- use dllPlugin & dllReferencePlugin
- turn off webpack devtool
- use HappyPack
- use babel-loader cache

But babel-loader not really effect the .vue file? right?

**Comment by qbaty** [comment] 2016-11-01 06:25
I do not think 17s is fast enough..

**Comment by yyx990803** [comment] 2016-11-05 04:01
Just curious, how many components are there in your app? And how many js dependencies do you have in the app?

**Comment by soliury** [comment] 2016-11-21 06:46
I have met this problem, and I use dll + HappyPack, it reduce from 63s to 13s, hot reload reduced from 13s to 3s. We have 50+ pages.

**Comment by qbaty** [comment] 2016-11-21 09:15
@soliury Does HappyPack effect the build performance ? 
I find HappyPack is not very helpful with vue-loader, I am not sure...
What is your config?

**Comment by soliury** [comment] 2016-11-21 10:43
HappyPack is helpful when the pages is large, it can effect the speed of babel. I think the dll is much more effective

**Comment by blake-newman** [comment] 2017-01-30 09:35
IMO I have found the greatest benefits to reduce compile times, is removing lint based loaders. Using Babel directory cache. 

Unfortunately as an application increases in size the greater the build times no matter the toolset in use. Vue-loader is very efficient, as it is essentially a mapping for other loaders.

So the more Babel/sass ect you use the slower the build times will be. This is out of vue-loader remit and if you didn't use vue-loader the difference is negligible.


For hot reloading, removing linters significantly helps this stat. 40s for a build is pretty good IMO as this is run once, hot reloading times are more worrying as they affect the dev experience.

**Comment by lanlin** [comment] 2017-02-13 01:42
vue-loader not working with happypack. [happaypack issues#83](https://github.com/amireh/happypack/issues/83)

**Comment by yyx990803** [comment] 2017-02-13 15:49
@lanlin I've identified the parts that make it incompatible, will likely be fixed in the next release.

**Comment by soliury** [comment] 2017-02-14 07:47
@yyx990803 good job.

**Comment by kazupon** [comment] 2017-02-14 08:26
Close (fixed v11.0.0)
https://github.com/vuejs/vue-loader/releases/tag/v11.0.0

**Comment by soliury** [comment] 2017-02-14 09:21
I have a try, but failed: 

This is the error: 
```
Module not found: Error: Can't resolve 'scss-loader' in 
```
My config is : 

```
            {
                test: /\.vue$/,
                loader: 'happypack/loader?id=vue',
                exclude: [
                    /node_modules/,
                    /vendor/
                ]
            }
```

**Comment by limichange** [comment] 2017-02-16 05:47
`vue-loader` and `happypack` is latest.

```bash
ERROR in ./src/pages/payPage/payPage.vue
Module build failed: AssertionError: HappyPack: plugin for the loader '1' could not be found! Did you forget to add it to the plugin list?
    at Object.HappyLoader (/Users/limi/tbsCode/moment-web-client/node_modules/happypack/lib/HappyLoader.js:29:3)
 @ ./src/pages/payPage/index.js 1:0-32
 @ ./src/pages/index.js
 @ ./src/router/index.js
 @ ./src/main.js
```

**Comment by soliury** [comment] 2017-02-16 10:09
@limichange I also meet the same error

**Comment by limichange** [comment] 2017-02-16 14:03
@kazupon Could you reopen this issue?

**Comment by yyx990803** [comment] 2017-02-16 20:31
So - the issue is not really in `vue-loader` now, but because HappyPack does not support non-serializable loader options/query, and also has a bug in serializing Object queries.

A workaround that **should** work is using `webpack.LoaderOptionsPlugin` to provide vue-loader options, but HappyPack doesn't seem to work with that either.

So for now there's nothing we can do on `vue-loader`'s side - I'll see if I can get a PR for HappyPack to improve this.

**Closed by yyx990803** 2017-02-16 20:31 UTC
Labels: improvement

**Comment by smith64fx** [comment] 2017-04-27 07:42
@limichange and @soliury 
I used to get over this error by just saying

    new HappyPack({
      id: '1', // instead of id: 'vue'
      loaders: [ 'vue-loader' ],
      threads: 4
    })

After that happy pack is found!
The only error I still get is this:

```
Object spread operator requires specified objectAssign option with 'Object.assign' or polyfill helper. (16:12)
```

I think this is because the vueConfig is not correctly assigned.. Gonna try to get over this..

**Comment by smith64fx** [comment] 2017-04-27 08:07
ok i managed it using this config here:

https://flyyang.github.io/2017/03/09/%E4%BD%BF%E7%94%A8happypack%E5%B0%86vuejs%E9%A1%B9%E7%9B%AEwebpack%E5%88%9D%E5%A7%8B%E5%8C%96%E6%9E%84%E5%BB%BA%E9%80%9F%E5%BA%A6%E6%8F%90%E5%8D%8750/

Unfortunately the build become slower instead of faster =/
This is maybe because I also use SSR.
