### ISSUE TITLE
CSS extraction with webpack4 does not work any more

### ISSUE THREAD

**Issue by Fohlen** [vuejs/vue-loader#1324] opened 2018-05-28 13:40 UTC
### Version
15.2.1

### Reproduction link
[https://gist.github.com/Fohlen/3385c87be56e06a1c730249d35fd6594](https://gist.github.com/Fohlen/3385c87be56e06a1c730249d35fd6594)

### Steps to reproduce
Set up a fresh project with webpack4 and vue-loader
Try to extract CSS

### What is expected?
CSS should be extracted

### What is actually happening?
Weird errors are thrown and CSS is not extracted

**Comment by Fohlen** [comment] 2018-05-28 13:41
Tried this without the `SplitChunks` plugin, neither did it work
Also putting `vue-loader` in the loader chain does not fix the issues

**Comment by yyx990803** [comment] 2018-05-28 13:46
You should replace `vue-style-loader` with the extract loader, not chaining after it.

**Comment by Fohlen** [comment] 2018-05-28 13:48
Then one should probably also update the docs at https://vue-loader.vuejs.org/guide/extract-css.html because they do not cover how this works

**Comment by yyx990803** [comment] 2018-05-28 13:51
It does:

``` js
process.env.NODE_ENV !== 'production'
            ? 'vue-style-loader'
            : MiniCssExtractPlugin.loader
```

**Comment by Fohlen** [comment] 2018-05-28 13:52
As I said before. This does produce an issue and does not work.

**Comment by yyx990803** [comment] 2018-05-28 13:53
Your original config is wrong... please read carefully.
CSS extraction is working properly per tests.

**Comment by Fohlen** [comment] 2018-05-28 13:57
You ought to be kidding me

```
const merge = require('webpack-merge')
const webpack = require('webpack')
const MiniCssExtractPlugin = require("mini-css-extract-plugin")
const common = require('./webpack.common')

module.exports = merge(common, {
  mode: 'production',
  plugins: [
      new webpack.optimize.SplitChunksPlugin(),
      new MiniCssExtractPlugin({
          filename: 'style.css'
      })
  ],
  module: {
      rules: [
          {
              test: /\.css$/,
              use: [
                  MiniCssExtractPlugin.loader,
                  'css-loader'
              ]
          }
      ]
  },
  devtool: '#source-map'
})
```

will __not__ produce a build. If you like me to, I can build a sample that will show that this fails.

**Comment by Fohlen** [comment] 2018-05-28 14:18
Probably should done this in the very first moment.
Here is a super simplistic `repl` demonstrating CSS extraction, as barebone as possible with web pack 4, https://repl.it/repls/DistantSweetInterchangeability
It will not work producing a valid bundle as documented.

**Comment by yyx990803** [comment] 2018-05-28 14:33
The problem is your usage of `webpack-merge`. The rules for css is duplicated in your merged config.

**Closed by yyx990803** 2018-05-28 14:33 UTC
