### ISSUE TITLE
windows10  npm run build   vue-loader@15.0.5  Module build failed: CssSyntaxError: 

### ISSUE THREAD

**Issue by crli** [vuejs/vue-loader#1280] opened 2018-05-02 03:26 UTC
### Version
15.0.0

### Reproduction link
[https://codesandbox.io/s/9ymm8mw9jo/](https://codesandbox.io/s/9ymm8mw9jo/)

### Steps to reproduce
npm i

npm run build  

### What is expected?
webpack build good

### What is actually happening?
 ERROR in ./src/App.vue?vue&type=style&index=0&lang=css (./node_modules/_vue-loader@15.0.5@vue-loader/lib/loaders/stylePostLoader.js!./node_modules/_vue-style-loader@4.1.0@vue-style-loader!./node_modules/_css-loader@0.28.11@css-loader!./node_modules/_vue-loader@15.0.5@vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=style&index=0&lang=css)
Module build failed: CssSyntaxError: E:\gitwork\qqqqqqq\src\App.vue:5:1: Unknown word

**Comment by Wbiokr** [comment] 2018-05-02 03:29
+1  CssSyntaxError  .

**Comment by kuoruan** [comment] 2018-05-02 03:30
+1

**Comment by yyx990803** [comment] 2018-05-02 21:09
Cannot reproduce. Your repro works fine for me (after renaming `src/main.js` to `src/index.js`). All tests are passing on Windows as well, so closing unless a valid repro can be provided.

**Closed by yyx990803** 2018-05-02 21:09 UTC

**Comment by crli** [comment] 2018-05-03 02:37
https://codesandbox.io/s/9ymm8mw9jo/ is fine but when `npm run build`  is not fine,

**Comment by Wbiokr** [comment] 2018-05-03 05:35
@crli 老铁，你的CssSyntaxError爆红处理好了吗

**Comment by crli** [comment] 2018-05-03 08:52
@Wbiokr 暂时用14.0.0了

**Comment by yyx990803** [comment] 2018-05-03 11:51
@crli I downloaded it and ran on a Windows 10 machine, and it also works fine. Make sure to provide actual reproduction.

**Comment by crli** [comment] 2018-05-03 14:53
https://github.com/crli/vueloader1505   node v8.11.1   npm 5.6.0 @yyx990803

**Comment by sen-miao** [comment] 2018-08-24 21:41
@yyx990803 @crli  There may be many `test: /\.css$/` or test: /\.less$/

**Comment by devkea** [comment] 2021-05-13 11:41
I use .scss files and some styles in the component like `<style scoped module lang="scss">`,
so, I replaced `test: /\.(s*)css$/,` to `/\.(sass|css)/` and it works for me!
