### ISSUE TITLE
Scoped style applied unexpectedly when root element receives conflicting class name from parent

### ISSUE THREAD

**Issue by connorspeers** [vuejs/vue-loader#1472] opened 2019-01-11 10:35 UTC
### Version
15.5.1

### Reproduction link
[https://codesandbox.io/s/oqjwl3zqnq](https://codesandbox.io/s/oqjwl3zqnq)

### Steps to reproduce
The code sandbox demonstrates the issue.

### What is expected?
The ".test" scoped class name only be applied to the inner div of the TestComponent.

### What is actually happening?
The ".test" scoped style is applied to both the inner div and the outer div in TestComponent, because the outer div receives the ".test" class name from the App parent component and has the applicable data-v-[hash] because it's in the same file as the scoped ".test" class name.

---
I noticed in the docs a [blurb](https://vue-loader.vuejs.org/guide/scoped-css.html#child-component-root-elements) that I think basically says this behavior is to be expected. However, I was padding some inputs and it took me a long time to figure out why I was seeing more padding that I had intended. It was because I was applying an ".input" class to my input component from the parent component, and inside that input component, I had also used the ".input" class to style the actual input element, which was not the root element (I wrapped it with a label). I don't personally feel that this behavior is expected.

I've thought a lot about potential solutions, but couldn't figure out one that would work without breaking changes to existing code.

For now, I'm using CSS modules, which doesn't have this problem. I am also considering using the [postcss-nested](https://github.com/postcss/postcss-nested) plugin, as I don't really care for how CSS modules read in my editor, and I think the nested css would look nice and fix the problem as well, but I haven't tested it yet. Something like this:

```vue
<template>
  <div class="root">
    <h1 class="child">whadup world</h1>
  </div>
</template>

<style scoped>
.root {
  padding: 2rem;

  .child {
    font-size: 2rem;
  }
}
</style>
```

**Comment by posva** [comment] 2019-01-11 11:39
Duplicate of #1460

**Comment by connorspeers** [comment] 2019-01-11 11:49
I don't believe this is a css specificity issue. The linked issue is an issue about two different classes overriding each other. My problem is that I want to use the same class name in two scoped components, but child component styles get unintentionally applied to the root element when I do this.

i.e. in the code sandbox, I would expect there to be one red border. Instead there is two. The -only- place a border style is defined is in the TestComponent, and I only apply that style one time in that component. Yet, two borders.

The simple fix is to not re-use the same class name across components to avoid any problems, but that defeats the purpose of scoped styles.

**Comment by posva** [comment] 2019-01-11 12:45
Oh indeed, I misunderstood!

**Comment by LinusBorg** [comment] 2019-01-24 08:31
While understandaly problematic, this is expected behaviour, and documented [here](https://vue-loader.vuejs.org/guide/scoped-css.html#child-component-root-elements), or more precisely logically follows from the way scoped css works.

There's not really anything to solve that on a technical level, if we want to keep scoped css working like it is (data attribute plus un-altered classnames)

**Closed** 2019-01-24 08:32 UTC
